import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SmartEmoji AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <Head>
        <meta charSet="UTF-8" />
      </Head>
      <body
        className={`${inter.className} antialiased relative`}
      >
        {children}
      </body>
    </html>
  );
}
